export interface GlobalSearchTarget {
  id: string
  title: string
  subtitle: string
  href: string
  keywords: string[]
}

export const GLOBAL_SEARCH_TARGETS: GlobalSearchTarget[] = [
  {
    id: 'dashboard',
    title: '仪表盘 Dashboard',
    subtitle: '核心财务指标与异常中心',
    href: '/dashboard/',
    keywords: ['首页', '驾驶舱', 'dashboard', '核心指标', '待办', '异常'],
  },
  {
    id: 'stores',
    title: '门店管理 Stores',
    subtitle: '门店经营表现与填报追踪',
    href: '/dashboard/stores/',
    keywords: ['门店', 'store', '填报', '经营健康', '排行'],
  },
  {
    id: 'stores-counters',
    title: '当口分析 Counters',
    subtitle: '时光新江南菜、金城兰舟、Shining Gourmet',
    href: '/dashboard/stores/counters/',
    keywords: ['当口', '档口', 'counter', '品牌档口', '毛利率', '损耗率'],
  },
  {
    id: 'hr',
    title: '人力系统 HR',
    subtitle: '编制、考勤、成本与绩效',
    href: '/dashboard/hr/',
    keywords: ['人力', 'hr', '考勤', '排班', '缺编', '人工成本'],
  },
  {
    id: 'hr-shift-optimization',
    title: '排班优化详情',
    subtitle: '门店班次与人工成本偏差明细',
    href: '/dashboard/hr/shift-optimization/',
    keywords: ['排班优化', '班次', '人工成本', 'shift', 'labor variance'],
  },
  {
    id: 'hr-staffing-gap',
    title: '缺编追踪详情',
    subtitle: '关键岗位缺口与补岗动作',
    href: '/dashboard/hr/staffing-gap/',
    keywords: ['缺编', '补岗', '招聘', '岗位缺口', 'staffing gap'],
  },
  {
    id: 'hr-exception-center',
    title: '人力异常中心',
    subtitle: '异常待办与 SLA 处置矩阵',
    href: '/dashboard/hr/exception-center/',
    keywords: ['人力异常', 'SLA', '待办', 'incident'],
  },
  {
    id: 'hr-gaia-roster',
    title: '盖雅花名册',
    subtitle: '全体员工清单与项目归属',
    href: '/dashboard/hr/gaia-roster/',
    keywords: ['盖雅', '花名册', '员工清单', 'gaia', '工号', '伙伴'],
  },
  {
    id: 'hr-project-staffing',
    title: '项目排班明细',
    subtitle: '按姓名追踪班次、成本、异常与排名',
    href: '/dashboard/hr/projects/',
    keywords: ['项目排班', '实时成本', '员工成本', '排名', 'staffing'],
  },
  {
    id: 'products',
    title: '产品中心 Product Center',
    subtitle: '菜品/饮品/周边/增值/其它 产品库',
    href: '/dashboard/products/',
    keywords: ['产品中心', '产品库', '菜品', '饮品', 'recipe', 'sop'],
  },
  {
    id: 'products-dishes',
    title: '产品中心 菜品',
    subtitle: '菜品产品库与配方管理',
    href: '/dashboard/products/category/dishes/',
    keywords: ['菜品', '菜系', '主食材', '烹饪方法', 'recipe'],
  },
  {
    id: 'products-beverages',
    title: '产品中心 饮品',
    subtitle: '饮品产品库与标准流程',
    href: '/dashboard/products/category/beverages/',
    keywords: ['饮品', '咖啡', '茶饮', '配方', 'sop'],
  },
  {
    id: 'products-peripheral',
    title: '产品中心 周边',
    subtitle: '周边商品库与成本结构',
    href: '/dashboard/products/category/peripheral/',
    keywords: ['周边', '商品', '衍生品', '成本'],
  },
  {
    id: 'products-value-added',
    title: '产品中心 增值',
    subtitle: '会员与企业服务产品库',
    href: '/dashboard/products/category/value-added/',
    keywords: ['增值', '会员', '企业服务', '套餐'],
  },
  {
    id: 'products-others',
    title: '产品中心 其它',
    subtitle: '季节限定与实验产品',
    href: '/dashboard/products/category/others/',
    keywords: ['其它', '季节限定', '实验产品', '新品'],
  },
  {
    id: 'supply',
    title: '供应链中心 Supply',
    subtitle: '采购、到货、质检与履约',
    href: '/dashboard/supply/',
    keywords: ['供应链', '采购', 'po', '到货', '质检', '冷链'],
  },
  {
    id: 'supply-procurement',
    title: '采购到货详情',
    subtitle: 'PO 明细、延迟与质检联动',
    href: '/dashboard/supply/procurement/',
    keywords: ['采购', '到货', 'po', '延迟订单', '质检'],
  },
  {
    id: 'supply-dispatch',
    title: '配送履约详情',
    subtitle: '路线履约与冷链预警',
    href: '/dashboard/supply/dispatch/',
    keywords: ['配送', '履约', '冷链', 'dispatch', 'route'],
  },
  {
    id: 'inventory',
    title: '库存中心 Inventory',
    subtitle: '库存周转、损耗与食安',
    href: '/dashboard/supply/inventory/',
    keywords: ['库存', '损耗', '食安', '效期', '周转'],
  },
  {
    id: 'inventory-alerts',
    title: '库存预警详情',
    subtitle: '原料库存风险与采购联动',
    href: '/dashboard/supply/inventory/alerts/',
    keywords: ['库存预警', '原料', '阈值', '补货'],
  },
  {
    id: 'inventory-food-safety',
    title: '食安闭环详情',
    subtitle: '巡检任务与整改闭环',
    href: '/dashboard/supply/inventory/food-safety/',
    keywords: ['食安', '巡检', '整改', '闭环'],
  },
  {
    id: 'finance',
    title: '财务分析 Finance',
    subtitle: '收入、成本、利润与结构',
    href: '/dashboard/finance/',
    keywords: ['财务', '利润', '成本', '税费', '管理费用'],
  },
  {
    id: 'executive',
    title: '高管协同指标 Executive',
    subtitle: 'CFO/CMO/CHRO/CGO/CAIO/CIO/CSCO',
    href: '/dashboard/executive/',
    keywords: ['高管', '协同指标', 'cfo', 'cmo', 'chro', 'cgo', 'caio', 'cto', 'cio', 'csco', '供应链'],
  },
  {
    id: 'executive-net-margin',
    title: '高管指标 净利率',
    subtitle: 'Executive KPI Net Margin',
    href: '/dashboard/executive/net_margin/',
    keywords: ['净利率', 'net margin', '高管指标', '利润率'],
  },
  {
    id: 'finance-revenue',
    title: '营业收入 Revenue',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/revenue/',
    keywords: ['营业收入', 'revenue', '营收'],
  },
  {
    id: 'finance-food-cost',
    title: '食材成本 Food Cost',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/food-cost/',
    keywords: ['食材成本', 'food cost', '原料成本'],
  },
  {
    id: 'finance-labor',
    title: '人工成本 Labor Cost',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/labor-cost/',
    keywords: ['人工成本', 'labor', '人力成本'],
  },
  {
    id: 'finance-net-profit',
    title: '净利润 Net Profit',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/net-profit/',
    keywords: ['净利润', 'net profit', '净利率'],
  },
  {
    id: 'finance-interest',
    title: '利息 Interest',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/interest/',
    keywords: ['利息', 'interest', '融资成本'],
  },
  {
    id: 'finance-depreciation',
    title: '折旧摊销 D&A',
    subtitle: '财务指标详情',
    href: '/dashboard/finance/depreciation-amortization/',
    keywords: ['折旧摊销', 'depreciation', 'amortization', 'd&a'],
  },
  {
    id: 'drilldown-global',
    title: '经营穿透 Global',
    subtitle: '全球口径下钻',
    href: '/dashboard/finance/drilldown/global/',
    keywords: ['经营穿透', '全球', 'drilldown', 'global'],
  },
  {
    id: 'drilldown-suzhou',
    title: '经营穿透 苏州',
    subtitle: '江苏-苏州城市口径',
    href: '/dashboard/finance/drilldown/global/china/east-china/jiangsu/suzhou/',
    keywords: ['苏州', 'suzhou', '华东', '江苏', '下钻'],
  },
  {
    id: 'drilldown-canteen',
    title: '经营穿透 A-sz011-碧迪二厂',
    subtitle: '门店级颗粒度',
    href: '/dashboard/finance/drilldown/global/china/east-china/jiangsu/suzhou/a-sz011-bidi-2/',
    keywords: ['碧迪二厂', 'a-sz011', '项目', '最细颗粒'],
  },
  {
    id: 'reports',
    title: '报表中心 Reports',
    subtitle: 'Excel / Word / PDF 导出',
    href: '/dashboard/reports/',
    keywords: ['报表', '导出', 'excel', 'word', 'pdf', '日报', '周报', '月报'],
  },
  {
    id: 'integrations',
    title: '系统集成 Integrations',
    subtitle: '盖雅、金蝶、小牛、美团接入',
    href: '/dashboard/integrations/',
    keywords: ['系统集成', '接口', '盖雅', '金蝶', '小牛', '美团', 'api'],
  },
  {
    id: 'integrations-llm',
    title: '模型接入 LLM Gateway',
    subtitle: 'DeepSeek / Gemma 4 / Kimi 2.5 / Llama / OpenAI / Claude',
    href: '/dashboard/integrations/llm/',
    keywords: ['llm', '模型', 'deepseek', 'gemma', 'kimi', 'llama', 'openai', 'claude', 'apikey'],
  },
  {
    id: 'oa-overview',
    title: '协同 OA 中心',
    subtitle: '对话、文件、通话、会议与审计',
    href: '/dashboard/oa/',
    keywords: ['oa', '协同', '对话', '文件', '通话', '会议', '审计'],
  },
  {
    id: 'oa-chat',
    title: 'OA 对话中心',
    subtitle: '项目群聊与消息留痕',
    href: '/dashboard/oa/chat/',
    keywords: ['oa聊天', '群聊', '消息', '沟通'],
  },
  {
    id: 'oa-contacts',
    title: 'OA 通讯录组织',
    subtitle: '联系人检索与组织架构管理',
    href: '/dashboard/oa/contacts/',
    keywords: ['通讯录', '联系人', '组织架构', '部门管理', '员工目录'],
  },
  {
    id: 'oa-files',
    title: 'OA 文件中枢',
    subtitle: '文件上传下载与追溯',
    href: '/dashboard/oa/files/',
    keywords: ['oa文件', '上传', '下载', '文档传输'],
  },
  {
    id: 'oa-calls',
    title: 'OA 通话中心',
    subtitle: '语音电话与视频电话',
    href: '/dashboard/oa/calls/',
    keywords: ['语音电话', '视频电话', '通话', '会议链接'],
  },
  {
    id: 'oa-meetings',
    title: 'OA 会议中心',
    subtitle: '会议安排与入会链接',
    href: '/dashboard/oa/meetings/',
    keywords: ['会议', '会议安排', '会议室', '加入会议'],
  },
  {
    id: 'oa-audit',
    title: 'OA 监控审计',
    subtitle: 'IP、地理位置与动作追踪',
    href: '/dashboard/oa/audit/',
    keywords: ['审计', 'ip', '地理位置', '监控', '日志'],
  },
  {
    id: 'admin',
    title: '管理员中心 Admin',
    subtitle: '权限治理与登录审计',
    href: '/dashboard/admin/',
    keywords: ['管理员', '权限', '审计', '登录记录', '用户管理'],
  },
  {
    id: 'documents',
    title: '知识库 Knowledge',
    subtitle: '文档资产与知识沉淀',
    href: '/dashboard/documents/',
    keywords: ['知识库', '文档', 'sop', '资料'],
  },
  {
    id: 'imports',
    title: '数据导入 Imports',
    subtitle: 'Word / Excel / PDF / 多模态源',
    href: '/dashboard/documents/imports/',
    keywords: ['导入', 'word', 'excel', 'pdf', '视频', '音频', '摄像头'],
  },
  {
    id: 'ai-agent',
    title: 'AI Agents Legion',
    subtitle: '高管智能体军团（12位CxO）',
    href: '/dashboard/agents/',
    keywords: ['ai', '智能体', 'agent', 'legion', '高管', 'cxo'],
  },
  {
    id: 'ai-workflows',
    title: 'AI 审批工单中心',
    subtitle: '任务审批、执行留痕与生成产物',
    href: '/dashboard/ai/workflows/',
    keywords: ['ai审批', '工单', '审批流程', '执行留痕', 'workflow'],
  },
  {
    id: 'ai-cap-contract-review',
    title: 'AI 能力 合同审阅',
    subtitle: '风险条款识别与改写建议',
    href: '/dashboard/chat/?capability=contract_review',
    keywords: ['合同审阅', '法务', '条款风险', '审阅'],
  },
  {
    id: 'ai-cap-policy',
    title: 'AI 能力 制度生成及更新',
    subtitle: '制度文档草拟与版本更新',
    href: '/dashboard/chat/?capability=policy_generation',
    keywords: ['制度', '制度生成', '制度更新', '流程制度'],
  },
  {
    id: 'ai-cap-tender',
    title: 'AI 能力 标书生成',
    subtitle: '投标方案与商务响应',
    href: '/dashboard/chat/?capability=tender_generation',
    keywords: ['标书', '投标', '招标', '提案'],
  },
  {
    id: 'ai-cap-report-summary',
    title: 'AI 能力 报告总结',
    subtitle: '管理层摘要与行动清单',
    href: '/dashboard/chat/?capability=report_summary',
    keywords: ['报告总结', '周报', '月报', '复盘'],
  },
  {
    id: 'ai-cap-copywriting',
    title: 'AI 能力 文案生成',
    subtitle: '活动文案与营销文案',
    href: '/dashboard/chat/?capability=copywriting',
    keywords: ['文案', '营销文案', '活动文案', '宣传文案'],
  },
  {
    id: 'ai-cap-product',
    title: 'AI 能力 产品生成',
    subtitle: '新品定位、成本结构与定价建议',
    href: '/dashboard/chat/?capability=product_generation',
    keywords: ['产品生成', '新品', '定价', '成本结构', '产品策划'],
  },
  {
    id: 'ai-cap-menu',
    title: 'AI 能力 菜单生成',
    subtitle: '菜单分层、菜品组合与毛利策略',
    href: '/dashboard/chat/?capability=menu_generation',
    keywords: ['菜单生成', '菜谱', '毛利', '菜单结构', '餐单'],
  },
  {
    id: 'ai-cap-audio',
    title: 'AI 能力 音频生成',
    subtitle: '播报脚本与 TTS 参数',
    href: '/dashboard/chat/?capability=audio_generation',
    keywords: ['音频', '播报', '配音', 'tts'],
  },
  {
    id: 'ai-cap-image',
    title: 'AI 能力 图片生成',
    subtitle: '图像提示词与构图规范',
    href: '/dashboard/chat/?capability=image_generation',
    keywords: ['图片', '图像生成', '海报', '视觉'],
  },
  {
    id: 'ai-cap-video',
    title: 'AI 能力 视频生成',
    subtitle: '视频脚本与分镜清单',
    href: '/dashboard/chat/?capability=video_generation',
    keywords: ['视频', '分镜', '短视频', '脚本'],
  },
  {
    id: 'ai-cap-social',
    title: 'AI 能力 社交媒体内容生成',
    subtitle: '多平台内容包与发布时间策略',
    href: '/dashboard/chat/?capability=social_content',
    keywords: ['社交媒体', '抖音', '小红书', '视频号', '公众号'],
  },
  {
    id: 'ai-cap-actuary',
    title: 'AI 能力 精算专家',
    subtitle: '经营测算、敏感性分析与利润推演',
    href: '/dashboard/chat/?capability=other',
    keywords: ['精算专家', '经营测算', '敏感性分析', '保本点', '利润模型'],
  },
  {
    id: 'settings',
    title: '系统设置 Settings',
    subtitle: '参数、安全与通知配置',
    href: '/dashboard/settings/',
    keywords: ['系统设置', '参数', '安全', '通知'],
  },
]

export const matchSearchTargets = (query: string, limit = 8) => {
  const normalized = query.trim().toLowerCase()
  if (!normalized) return [] as GlobalSearchTarget[]

  return GLOBAL_SEARCH_TARGETS.filter((target) => {
    const fullText = `${target.title} ${target.subtitle} ${target.keywords.join(' ')}`.toLowerCase()
    return fullText.includes(normalized)
  }).slice(0, limit)
}
