export type ProjectStrategicLevel = 'VVIP' | 'KA' | 'VIP'

export interface CateringProjectDirectoryItem {
  siteSlug: string
  name: string
  city: string
  strategicLevel: ProjectStrategicLevel
  owner: string
  ownerTitle: string
  scopePath: string[]
}

const NORTH_CHINA_PREFIX = ['global', 'china', 'north-china'] as const
const EAST_CHINA_PREFIX = ['global', 'china', 'east-china'] as const
const JIANGSU_PREFIX = ['global', 'china', 'east-china', 'jiangsu'] as const

export const REAL_CATERING_PROJECTS: CateringProjectDirectoryItem[] = [
  {
    siteSlug: 'a-sz011-bidi-2',
    name: 'A-sz011-碧迪二厂',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '高满亮 Charlie',
    ownerTitle: '运营经理·江苏一区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz011-bidi-2'],
  },
  {
    siteSlug: 'a-sz012-yingbaida',
    name: 'A-sz012-英佰达医疗',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '高满亮 Charlie',
    ownerTitle: '运营经理·江苏一区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz012-yingbaida'],
  },
  {
    siteSlug: 'a-sz037-youda',
    name: 'A-sz037-友达光电',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '高满亮 Charlie',
    ownerTitle: '运营经理·江苏一区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz037-youda'],
  },
  {
    siteSlug: 'a-sz027-aifake',
    name: 'A-sz027-爱发科',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '高满亮 Charlie',
    ownerTitle: '运营经理·江苏一区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz027-aifake'],
  },
  {
    siteSlug: 'a-sz049-huichuan',
    name: 'A-sz049-汇川',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '刘欢',
    ownerTitle: '运营经理·江苏二区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz049-huichuan'],
  },
  {
    siteSlug: 'a-sz043-lilly',
    name: 'A-sz043-礼来制药',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '刘欢',
    ownerTitle: '运营经理·江苏二区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz043-lilly'],
  },
  {
    siteSlug: 'a-sz001-baide',
    name: 'A-sz001-百得',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '刘欢',
    ownerTitle: '运营经理·江苏二区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz001-baide'],
  },
  {
    siteSlug: 'a-sz051-debi',
    name: 'A-sz051-德比',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '刘欢',
    ownerTitle: '运营经理·江苏二区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz051-debi'],
  },
  {
    siteSlug: 'a-sz015-nuodu',
    name: 'A-sz015-挪度',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '郑敏薇 Aviel',
    ownerTitle: '运营经理·江苏三区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz015-nuodu'],
  },
  {
    siteSlug: 'a-sz021-yitaibo',
    name: 'A-sz021-易泰博',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '郑敏薇 Aviel',
    ownerTitle: '运营经理·江苏三区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz021-yitaibo'],
  },
  {
    siteSlug: 'a-sz010-sailangtaike',
    name: 'A-sz010-赛琅泰克',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '郑敏薇 Aviel',
    ownerTitle: '运营经理·江苏三区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz010-sailangtaike'],
  },
  {
    siteSlug: 'a-sz036-kerui',
    name: 'A-sz036-科瑞',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '郑敏薇 Aviel',
    ownerTitle: '运营经理·江苏三区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz036-kerui'],
  },
  {
    siteSlug: 'a-sz046-yiteng',
    name: 'A-sz046-亿腾医药',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '郑敏薇 Aviel',
    ownerTitle: '运营经理·江苏三区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz046-yiteng'],
  },
  {
    siteSlug: 'a-sz030-huishi',
    name: 'A-sz030-惠氏',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '程永梅 Lisa',
    ownerTitle: '运营总监·江苏四区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz030-huishi'],
  },
  {
    siteSlug: 'a-sz038-fushi-jiaopian',
    name: 'A-sz038-富士胶片',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '程永梅 Lisa',
    ownerTitle: '运营总监·江苏四区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz038-fushi-jiaopian'],
  },
  {
    siteSlug: 'a-sz047-zhongou',
    name: 'A-sz047-中欧',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '程永梅 Lisa',
    ownerTitle: '运营总监·江苏四区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz047-zhongou'],
  },
  {
    siteSlug: 'a-sz048-huashuo',
    name: 'A-sz048-华硕科技',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '程永梅 Lisa',
    ownerTitle: '运营总监·江苏四区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz048-huashuo'],
  },
  {
    siteSlug: 'a-sz053-ngk',
    name: 'A-sz053-NGK',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '程永梅 Lisa',
    ownerTitle: '运营总监·江苏四区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz053-ngk'],
  },
  {
    siteSlug: 'a-sz003-endes',
    name: 'A-sz003-恩德斯豪斯二厂',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '宋玉 Anne',
    ownerTitle: '运营总监·江苏五区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz003-endes'],
  },
  {
    siteSlug: 'a-sz013-dinuola',
    name: 'A-sz013-迪诺拉',
    city: '苏州',
    strategicLevel: 'KA',
    owner: '宋玉 Anne',
    ownerTitle: '运营总监·江苏五区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'a-sz013-dinuola'],
  },
  {
    siteSlug: 'bluefish-suzhou-xinghai',
    name: '蓝枪鱼苏州星海店',
    city: '苏州',
    strategicLevel: 'VVIP',
    owner: '宋玉 Anne',
    ownerTitle: '运营总监·江苏五区',
    scopePath: [...JIANGSU_PREFIX, 'suzhou', 'bluefish-suzhou-xinghai'],
  },
  {
    siteSlug: 'a-wx005-cuntian',
    name: 'A-wx005-村田电子',
    city: '无锡',
    strategicLevel: 'VIP',
    owner: '宋玉 Anne',
    ownerTitle: '运营总监·江苏五区',
    scopePath: [...JIANGSU_PREFIX, 'wuxi', 'a-wx005-cuntian'],
  },
  {
    siteSlug: 'a-sh032-ximalaya',
    name: 'A-sh032-喜玛拉雅',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海一区负责人',
    ownerTitle: '运营经理·上海一区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh032-ximalaya'],
  },
  {
    siteSlug: 'a-sh035-shefule-anting',
    name: 'A-sh035-舍弗勒-安亭',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海一区负责人',
    ownerTitle: '运营经理·上海一区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh035-shefule-anting'],
  },
  {
    siteSlug: 'a-sh037-huazhu',
    name: 'A-sh037-华住',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海一区负责人',
    ownerTitle: '运营经理·上海一区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh037-huazhu'],
  },
  {
    siteSlug: 'bluefish-shanghai-huazhu',
    name: '蓝枪鱼上海华住店',
    city: '上海',
    strategicLevel: 'VVIP',
    owner: '上海一区负责人',
    ownerTitle: '运营经理·上海一区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'bluefish-shanghai-huazhu'],
  },
  {
    siteSlug: 'bluefish-shanghai-biyun',
    name: '蓝枪鱼上海碧云店',
    city: '上海',
    strategicLevel: 'VVIP',
    owner: '上海一区负责人',
    ownerTitle: '运营经理·上海一区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'bluefish-shanghai-biyun'],
  },
  {
    siteSlug: 'a-sh038-meidi',
    name: 'A-sh038-美的',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海二区负责人',
    ownerTitle: '运营经理·上海二区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh038-meidi'],
  },
  {
    siteSlug: 'a-sh039-zhengxin',
    name: 'A-sh039-征信中心',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海二区负责人',
    ownerTitle: '运营经理·上海二区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh039-zhengxin'],
  },
  {
    siteSlug: 'a-sh040-kaizhong',
    name: 'A-sh040-上海凯众',
    city: '上海',
    strategicLevel: 'KA',
    owner: '上海二区负责人',
    ownerTitle: '运营经理·上海二区',
    scopePath: [...EAST_CHINA_PREFIX, 'shanghai', 'a-sh040-kaizhong'],
  },
  {
    siteSlug: 'a-sh036-shefule-taicang',
    name: 'A-sh036-舍弗勒-太仓',
    city: '太仓',
    strategicLevel: 'VIP',
    owner: '上海二区负责人',
    ownerTitle: '运营经理·上海二区',
    scopePath: [...JIANGSU_PREFIX, 'taicang', 'a-sh036-shefule-taicang'],
  },
  {
    siteSlug: 'a-bj035-zf',
    name: 'A-bj035-北京采埃孚',
    city: '北京',
    strategicLevel: 'KA',
    owner: '华北一区负责人',
    ownerTitle: '运营经理·华北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'beijing', 'a-bj035-zf'],
  },
  {
    siteSlug: 'a-bj055-huichuan',
    name: 'A-bj055-北京汇川',
    city: '北京',
    strategicLevel: 'KA',
    owner: '华北一区负责人',
    ownerTitle: '运营经理·华北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'beijing', 'a-bj055-huichuan'],
  },
  {
    siteSlug: 'a-sz044-envision-chifeng',
    name: 'A-sz044-远景动力（赤峰）',
    city: '赤峰',
    strategicLevel: 'VIP',
    owner: '华北一区负责人',
    ownerTitle: '运营经理·华北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'chifeng', 'a-sz044-envision-chifeng'],
  },
  {
    siteSlug: 'a-sz039-envision-ordos',
    name: 'A-sz039-远景动力（鄂尔多斯）',
    city: '鄂尔多斯',
    strategicLevel: 'VIP',
    owner: '西北一区负责人',
    ownerTitle: '运营经理·西北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'ordos', 'a-sz039-envision-ordos'],
  },
  {
    siteSlug: 'a-sz045-crrc-ordos',
    name: 'A-sz045-中车（鄂尔多斯）',
    city: '鄂尔多斯',
    strategicLevel: 'VIP',
    owner: '西北一区负责人',
    ownerTitle: '运营经理·西北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'ordos', 'a-sz045-crrc-ordos'],
  },
  {
    siteSlug: 'a-sz052-inner-mongolia-huadian',
    name: 'A-sz052-内蒙华典',
    city: '鄂尔多斯',
    strategicLevel: 'VIP',
    owner: '西北一区负责人',
    ownerTitle: '运营经理·西北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'ordos', 'a-sz052-inner-mongolia-huadian'],
  },
  {
    siteSlug: 'a-sz040-envision-shiyan',
    name: 'A-sz040-远景动力（湖北十堰）',
    city: '十堰',
    strategicLevel: 'VIP',
    owner: '西北二区负责人',
    ownerTitle: '运营经理·西北二区',
    scopePath: [...NORTH_CHINA_PREFIX, 'shiyan', 'a-sz040-envision-shiyan'],
  },
  {
    siteSlug: 'a-dl001-dalian-airport',
    name: 'A-DL001-大连机场',
    city: '大连',
    strategicLevel: 'VIP',
    owner: '华北一区负责人',
    ownerTitle: '运营经理·华北一区',
    scopePath: [...NORTH_CHINA_PREFIX, 'dalian', 'a-dl001-dalian-airport'],
  },
]

